# Константы для приложения users
FIRST_NAME_LENGTH = 150
LAST_NAME_LENGTH = 150
PASSWORD_LENGTH = 150

# Константы для приложения recipes
INGREDIENT_NAME_LENGTH = 64
INGREDIENT_UNIT_LENGTH = 32
TAG_COLOR_LENGTH = 7
TAG_NAME_LENGTH = 32
RECIPE_NAME_LENGTH = 200
